import type { TaskRecord } from './task-types'

export const seedTasks: TaskRecord[] = [
  {
    id: 'task-kanban-dnd',
    title: '看板拖拽稳定性回归',
    summary: '验证列内重排、跨列迁移和空列投放行为，补充边界测试。',
    status: 'doing',
    priority: 'P0',
    owner: 'AI',
    projectName: 'Workspace 看板',
    tags: ['Kanban', 'DnD', 'QA'],
    updatedAt: '2026-02-28T18:20:00+08:00',
    updatedAtLabel: '今天 18:20',
    dueAt: '2026-03-01',
    dueAtLabel: '3 月 1 日',
    estimateHours: 3
  },
  {
    id: 'task-kanban-task-model',
    title: '看板实体从 Project 切换为 Task',
    summary: '统一任务字段和状态流，避免项目字段污染看板交互。',
    status: 'doing',
    priority: 'P0',
    owner: 'Lucas + AI',
    projectName: 'Workspace 看板',
    tags: ['Refactor', 'Model'],
    updatedAt: '2026-02-28T19:10:00+08:00',
    updatedAtLabel: '今天 19:10',
    dueAt: '2026-03-01',
    dueAtLabel: '3 月 1 日',
    estimateHours: 2
  },
  {
    id: 'task-kanban-status-policy',
    title: '补状态迁移策略配置',
    summary: '定义 backlog/todo/doing/in-review/done/canceled 允许迁移矩阵。',
    status: 'todo',
    priority: 'P1',
    owner: 'AI',
    projectName: 'Workspace 看板',
    tags: ['Rules', 'Workflow'],
    updatedAt: '2026-02-28T17:40:00+08:00',
    updatedAtLabel: '今天 17:40',
    dueAt: '2026-03-03',
    dueAtLabel: '3 月 3 日',
    estimateHours: 4
  },
  {
    id: 'task-kanban-empty-state',
    title: '看板空列提示优化',
    summary: '空列提示增加引导文案，降低新用户理解成本。',
    status: 'todo',
    priority: 'P2',
    owner: 'Lucas',
    projectName: 'Workspace UX',
    tags: ['UX', 'Copy'],
    updatedAt: '2026-02-28T16:55:00+08:00',
    updatedAtLabel: '今天 16:55',
    dueAt: '2026-03-05',
    dueAtLabel: '3 月 5 日',
    estimateHours: 1
  },
  {
    id: 'task-kanban-doc-sync',
    title: '同步看板迁移文档',
    summary: '更新 docs/plans，明确任务看板和项目仪表盘边界。',
    status: 'in-review',
    priority: 'P1',
    owner: 'AI',
    projectName: 'Tech Docs',
    tags: ['Docs'],
    updatedAt: '2026-02-28T19:20:00+08:00',
    updatedAtLabel: '今天 19:20',
    dueAt: '2026-03-02',
    dueAtLabel: '3 月 2 日',
    estimateHours: 1
  },
  {
    id: 'task-kanban-model-env',
    title: '模型配置页接入环境校验',
    summary: '在保存时校验 API Key/Base URL，减少运行时报错。',
    status: 'backlog',
    priority: 'P1',
    owner: 'Lucas',
    projectName: 'Settings',
    tags: ['Model', 'Validation'],
    updatedAt: '2026-02-28T15:30:00+08:00',
    updatedAtLabel: '今天 15:30',
    dueAt: '2026-03-06',
    dueAtLabel: '3 月 6 日',
    estimateHours: 3
  },
  {
    id: 'task-kanban-release-check',
    title: '发布前 smoke 测试清单',
    summary: '检查设置页、文件页、看板页、Draw Studio 的核心路径。',
    status: 'done',
    priority: 'P1',
    owner: 'AI',
    projectName: 'Release',
    tags: ['Release', 'QA'],
    updatedAt: '2026-02-28T13:50:00+08:00',
    updatedAtLabel: '今天 13:50',
    dueAt: '2026-02-28',
    dueAtLabel: '2 月 28 日',
    estimateHours: 2
  },
  {
    id: 'task-kanban-canvas-compat',
    title: 'Canvas 历史 schema 兼容',
    summary: '梳理旧格式差异并提供降级渲染方案。',
    status: 'canceled',
    priority: 'P2',
    owner: '前端',
    projectName: 'Canvas',
    tags: ['Canvas', 'Schema'],
    updatedAt: '2026-02-27T21:10:00+08:00',
    updatedAtLabel: '昨天 21:10',
    dueAt: '2026-03-07',
    dueAtLabel: '3 月 7 日',
    blockedReason: '当前版本优先级下调，迁移窗口后置。'
  }
]
